const $=id=>document.getElementById(id), pad=n=>String(n).padStart(2,'0');
const dateKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const parseDate=s=>{const [y,m,d]=s.split('-').map(Number);return new Date(y,m-1,d)};
const addDays=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const today=new Date(), todayKey=dateKey(today), STORAGE='yueji-archive-v1';
const palette=['#5f8f7b','#567fae','#9272ad','#c87d95','#c88955','#7d7065'];
const demo={source:'演示数据',accent:'#5f8f7b',challengeStart:`${today.getFullYear()}-01-01`,challengeEnd:`${today.getFullYear()}-12-31`,books:[
 {key:'crime',title:'罪与罚',file:'罪与罚.epub',author:'陀思妥耶夫斯基',category:'文学',country:'俄罗斯',birth:1821,progress:38,status:'reading',minutes:426,words:93000,days:8,color:'#6f5b4e'},
 {key:'art',title:'艺术的故事',file:'艺术的故事.azw3',author:'E. H. 贡布里希',category:'艺术',country:'英国',birth:1909,progress:16,status:'reading',minutes:188,words:41000,days:5,color:'#66788d'},
 {key:'deadpool',title:'Deadpool Classic',file:'Deadpool Classic.cbz',author:'Fabian Nicieza',category:'漫画',country:'美国',birth:1961,progress:27,status:'reading',minutes:246,words:18000,days:6,color:'#934f4f'},
 {key:'stranger',title:'局外人',file:'局外人.epub',author:'阿尔贝·加缪',category:'文学',country:'法国',birth:1913,progress:100,status:'done',minutes:220,words:52000,days:4,color:'#8b8662'}],sessions:[],journals:{},importedAt:''};
for(let i=0;i<18;i++){const d=addDays(today,-i*2);const b=demo.books[i%demo.books.length];demo.sessions.push({date:dateKey(d),bookKey:b.key,minutes:18+(i*7)%49,words:1800+(i*733)%5200})}
demo.journals[todayKey]={date:todayKey,bookKey:'crime',read:true,what:'《罪与罚》第三章',quote:'人能够适应一切。',thought:'越往下读越觉得，拉斯柯尔尼科夫真正承受不住的并不是罪，而是他无法继续相信自己对罪的解释。'};
let state=load();let page='today',libraryFilter='all';
function clone(v){return JSON.parse(JSON.stringify(v))}
function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE));if(x)return normalize(x)}catch(e){}return clone(demo)}
function normalize(x){return {...clone(demo),...x,books:Array.isArray(x.books)?x.books:[],sessions:Array.isArray(x.sessions)?x.sessions:[],journals:x.journals||{},highlights:Array.isArray(x.highlights)?x.highlights:[]}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(state))}
function rgb(hex){const h=hex.replace('#','');const n=parseInt(h,16);return `${n>>16&255},${n>>8&255},${n&255}`}
function applyAccent(){document.documentElement.style.setProperty('--accent',state.accent);document.documentElement.style.setProperty('--accent-rgb',rgb(state.accent));document.querySelectorAll('[data-color]').forEach(b=>b.classList.toggle('active',b.dataset.color===state.accent));$('customColor').value=state.accent}
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>t.classList.remove('show'),1800)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function fmtDate(key){const d=parseDate(key);return `${d.getFullYear()}年${d.getMonth()+1}月${d.getDate()}日`}
function book(key){return state.books.find(b=>b.key===key)}
function dayData(key){const ss=state.sessions.filter(s=>s.date===key),j=state.journals[key];return {sessions:ss,journal:j,read:ss.length>0||!!j?.read,minutes:ss.reduce((a,b)=>a+(+b.minutes||0),0),words:ss.reduce((a,b)=>a+(+b.words||0),0),books:new Set(ss.map(s=>s.bookKey).filter(Boolean))}}
function switchPage(p){page=p;document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===p));document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.go===p));if(p==='analytics')renderAnalytics();if(p==='monthly')renderMonthly()}
document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>switchPage(b.dataset.go));
function renderToday(){const d=dayData(todayKey);$('todayDate').textContent=fmtDate(todayKey);$('todayMinutes').textContent=d.minutes;$('todayBooks').textContent=d.books.size;$('todayWords').textContent=d.words.toLocaleString('zh-CN');$('todayMark').textContent=d.read?'✓':'📖';const j=d.journal;$('todayJournal').className='journal-preview'+(j?.thought?'':' empty-text');$('todayJournal').textContent=j?.thought||'今天还没有写感悟。';$('todayBookList').innerHTML=d.sessions.length?d.sessions.map(s=>{const b=book(s.bookKey);return `<div class="mini-book"><div><b>${esc(b?.title||s.title||'未命名书籍')}</b><span>${+s.minutes||0} 分钟 · ${(+s.words||0).toLocaleString('zh-CN')} 字</span></div><div class="progress-track"><div class="progress-fill" style="width:${Math.min(100,b?.progress||0)}%"></div></div></div>`}).join(''):'<div class="empty-text">今天还没有来自静读天下的阅读记录。</div>';renderCalendar()}
function renderCalendar(){const wrap=$('challengeGrid');wrap.innerHTML='';const start=parseDate(state.challengeStart),end=parseDate(state.challengeEnd);let cur=new Date(start.getFullYear(),start.getMonth(),1),count=0,safety=0;while(cur<=end&&safety++<24){const y=cur.getFullYear(),m=cur.getMonth(),first=(new Date(y,m,1).getDay()+6)%7,last=new Date(y,m+1,0).getDate();const el=document.createElement('div');el.className='month-block';el.innerHTML=`<div class="month-name">${y!==start.getFullYear()?y+' · ':''}${m+1}月</div>`;const grid=document.createElement('div');grid.className='month-days';for(let i=0;i<first;i++){const x=document.createElement('i');x.className='cal-day out';grid.append(x)}for(let n=1;n<=last;n++){const key=dateKey(new Date(y,m,n)),dd=dayData(key);const b=document.createElement('button');b.className='cal-day';if(key<state.challengeStart||key>state.challengeEnd)b.classList.add('out');if(dd.read){b.classList.add('read');count++}if(dd.journal?.thought||dd.journal?.quote)b.classList.add('note');if(key===todayKey)b.classList.add('today');b.title=fmtDate(key);b.onclick=()=>openJournal(key);grid.append(b)}el.append(grid);wrap.append(el);cur=new Date(y,m+1,1)}$('challengeRead').textContent=count}
function statusOf(b){if(b.status)return b.status;if(+b.progress>=100)return'done';if(+b.progress>0)return'reading';return'unread'}
function renderLibrary(){const q=$('bookSearch').value.trim().toLowerCase();const arr=state.books.filter(b=>(libraryFilter==='all'||statusOf(b)===libraryFilter)&&`${b.title} ${b.file||''} ${b.author||''}`.toLowerCase().includes(q));$('libraryCount').textContent=state.books.length;$('bookshelf').innerHTML=arr.length?arr.map((b,i)=>`<button class="spine" data-book="${esc(b.key)}" style="height:${145+(i%4)*18}px;background:${b.color||palette[i%palette.length]}">${esc(b.title)}</button>`).join(''):'<div class="empty-text">这里还没有书。导入静读天下备份后，书架会自动出现。</div>';$('bookTable').innerHTML=arr.map(b=>`<button class="book-row" data-book="${esc(b.key)}"><div><b>${esc(b.title)}</b><span>${esc(b.author||b.file||'待补充作者')}</span></div><div><b>${Math.round(+b.progress||0)}%</b><span>${statusOf(b)==='done'?'已读':statusOf(b)==='reading'?'在读':'未读'}</span></div></button>`).join('');document.querySelectorAll('[data-book]').forEach(x=>x.onclick=()=>openBook(x.dataset.book))}
$('bookSearch').oninput=renderLibrary;$('librarySeg').onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;libraryFilter=b.dataset.filter;document.querySelectorAll('#librarySeg button').forEach(x=>x.classList.toggle('active',x===b));renderLibrary()};
function renderNotes(){const q=$('noteSearch').value.trim().toLowerCase(),bk=$('noteBookFilter').value;const journals=Object.values(state.journals).filter(j=>(!bk||j.bookKey===bk)&&`${j.what||''} ${j.quote||''} ${j.thought||''}`.toLowerCase().includes(q)).map(j=>({...j,type:'journal',sortTime:parseDate(j.date).getTime()}));const highlights=(state.highlights||[]).filter(h=>(!bk||h.bookKey===bk)&&`${h.quote||''} ${h.note||''} ${h.bookmark||''}`.toLowerCase().includes(q)).map(h=>({...h,type:'highlight',sortTime:+h.time||parseDate(h.date).getTime()}));const arr=[...journals,...highlights].sort((a,b)=>b.sortTime-a.sortTime);$('notesList').innerHTML=arr.length?arr.map(n=>n.type==='journal'?`<article class="note-card" data-note="${n.date}"><div class="note-meta">${fmtDate(n.date)}${n.bookKey&&book(n.bookKey)?' · '+esc(book(n.bookKey).title):''} · 阅读手记</div>${n.what?`<b>${esc(n.what)}</b>`:''}${n.quote?`<blockquote>${esc(n.quote)}</blockquote>`:''}${n.thought?`<p>${esc(n.thought)}</p>`:''}</article>`:`<article class="note-card moon-highlight"><div class="note-meta">${fmtDate(n.date)}${n.bookKey&&book(n.bookKey)?' · '+esc(book(n.bookKey).title):''} · 静读书摘${n.bookmark?' · '+esc(n.bookmark):''}</div><blockquote>${esc(n.quote)}</blockquote>${n.note?`<p>${esc(n.note)}</p>`:''}</article>`).join(''):'<div class="card empty-text">没有符合条件的笔记。</div>';document.querySelectorAll('[data-note]').forEach(x=>x.onclick=()=>openJournal(x.dataset.note))}
$('noteSearch').oninput=renderNotes;$('noteBookFilter').onchange=renderNotes;
function renderBookOptions(){const opts='<option value="">不指定</option>'+state.books.map(b=>`<option value="${esc(b.key)}">${esc(b.title)}</option>`).join('');$('journalBook').innerHTML=opts;$('noteBookFilter').innerHTML='<option value="">全部书籍</option>'+state.books.map(b=>`<option value="${esc(b.key)}">${esc(b.title)}</option>`).join('')}
function renderAnalytics(){const total=state.sessions.reduce((a,s)=>a+(+s.minutes||0),0),words=state.sessions.reduce((a,s)=>a+(+s.words||0),0),days=new Set(state.sessions.map(s=>s.date));$('kpiGrid').innerHTML=[['累计阅读',total.toLocaleString(),'分钟'],['阅读天数',days.size,'天'],['书架',state.books.length,'本'],['阅读字数',words.toLocaleString(),'字']].map(x=>`<div class="kpi"><b>${x[1]}</b><span>${x[0]} · ${x[2]}</span></div>`).join('');const cats={};state.books.forEach(b=>cats[b.category||'未分类']=(cats[b.category||'未分类']||0)+1);const entries=Object.entries(cats).sort((a,b)=>b[1]-a[1]);$('categoryTreemap').innerHTML=entries.map((x,i)=>`<div class="tree-cell" style="background:${palette[i%palette.length]}"><b>${esc(x[0])}</b><span>${x[1]}</span></div>`).join('');$('categoryLegend').innerHTML=entries.map(x=>`<span>● ${esc(x[0])} ${x[1]}</span>`).join('');const groups=[['未开始',b=>+b.progress===0],['1—25%',b=>+b.progress>0&&+b.progress<=25],['26—50%',b=>+b.progress>25&&+b.progress<=50],['51—99%',b=>+b.progress>50&&+b.progress<100],['已读完',b=>+b.progress>=100]];$('progressBars').innerHTML=groups.map(([n,f])=>{const c=state.books.filter(f).length,p=state.books.length?c/state.books.length*100:0;return `<div class="bar-row"><span>${n}</span><div class="bar"><i style="width:${p}%"></i></div><b>${c}</b></div>`}).join('');const months=Array.from({length:12},(_,i)=>{const k=`${today.getFullYear()}-${pad(i+1)}`,mins=state.sessions.filter(s=>s.date.startsWith(k)).reduce((a,s)=>a+(+s.minutes||0),0);return {i,mins}}),max=Math.max(1,...months.map(x=>x.mins));$('timelineHeat').innerHTML=months.map(x=>`<div class="heat-month" style="--a:${.08+.65*x.mins/max}" title="${x.mins} 分钟">${x.i+1}月</div>`).join('')}
function renderMonthly(){const val=$('monthPicker').value||todayKey.slice(0,7),[y,m]=val.split('-').map(Number),ss=state.sessions.filter(s=>s.date.startsWith(val)),mins=ss.reduce((a,s)=>a+(+s.minutes||0),0),words=ss.reduce((a,s)=>a+(+s.words||0),0),keys=[...new Set(ss.map(s=>s.bookKey))],seen=keys.map(book).filter(Boolean);$('monthlyTitle').textContent=`${y}年${m}月 · 阅读月报`;$('monthlyKpis').innerHTML=[['阅读时长',mins,'分钟'],['阅读天数',new Set(ss.map(s=>s.date)).size,'天'],['看过',seen.length,'本'],['阅读字数',words.toLocaleString(),'字']].map(x=>`<div class="monthly-kpi"><b>${x[1]}</b><span>${x[0]} · ${x[2]}</span></div>`).join('');$('monthSeenTitle').textContent=`本月看过 · ${seen.length} 本`;$('monthSeenBooks').innerHTML=seen.length?seen.map((b,i)=>`<div class="month-book" style="background:${b.color||palette[i%palette.length]}"><b>${esc(b.title)}</b><small>${esc(b.author||'')}</small></div>`).join(''):'<div class="empty-text">这个月还没有阅读记录。</div>';const count={};ss.forEach(s=>count[s.bookKey]=(count[s.bookKey]||0)+(+s.minutes||0));const top=Object.entries(count).sort((a,b)=>b[1]-a[1])[0];$('monthTopBook').innerHTML=top?`<b>${esc(book(top[0])?.title||'未命名')}</b><div class="section-sub">${top[1]} 分钟</div>`:'<div class="empty-text">暂无</div>';const done=seen.filter(b=>statusOf(b)==='done');$('monthFinished').innerHTML=done.length?done.map(b=>`<div>${esc(b.title)}</div>`).join(''):'<div class="empty-text">暂无</div>';$('monthSummary').textContent=mins?`这个月一共读了 ${mins} 分钟，留下了 ${Object.values(state.journals).filter(j=>j.date.startsWith(val)).length} 篇手记。读得最多的是${top?'《'+(book(top[0])?.title||'未命名')+'》':'—'}。`:'这个月还没有可供总结的记录。'}
$('monthPicker').value=todayKey.slice(0,7);$('monthPicker').onchange=renderMonthly;
const overlay=$('overlay'),sheets=[...document.querySelectorAll('.sheet')];function showSheet(id){overlay.classList.add('show');$(id).classList.add('show')}function closeSheets(){overlay.classList.remove('show');sheets.forEach(s=>s.classList.remove('show'))}overlay.onclick=closeSheets;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=closeSheets);
$('settingsBtn').onclick=()=>{$('challengeStart').value=state.challengeStart;$('challengeEnd').value=state.challengeEnd;showSheet('settingsSheet')};
function openJournal(key){const j=state.journals[key]||{date:key};$('journalOriginalDate').value=key;$('journalDate').value=key;$('journalBook').value=j.bookKey||'';$('journalRead').checked=!!j.read;$('journalWhat').value=j.what||'';$('journalQuote').value=j.quote||'';$('journalThought').value=j.thought||'';$('journalSheetTitle').textContent=fmtDate(key);showSheet('journalSheet')}
$('editTodayBtn').onclick=()=>openJournal(todayKey);$('saveJournal').onclick=()=>{const old=$('journalOriginalDate').value,key=$('journalDate').value;if(!key){toast('请选择日期');return}if(old!==key)delete state.journals[old];state.journals[key]={date:key,bookKey:$('journalBook').value,read:$('journalRead').checked,what:$('journalWhat').value.trim(),quote:$('journalQuote').value.trim(),thought:$('journalThought').value.trim()};save();renderAll();closeSheets();toast('这一天已保存')};
function openBook(key){const b=book(key);if(!b)return;$('bookKey').value=b.key;$('bookTitle').value=b.title||'';$('bookAuthor').value=b.author||'';$('bookCategory').value=b.category||'';$('bookProgress').value=b.progress??'';$('bookDataNote').textContent=`静读天下文件：${b.file||'—'} · 累计 ${b.minutes||0} 分钟 · ${b.days||0} 个阅读日`;$('bookSheetTitle').textContent=b.title;showSheet('bookSheet')}
$('saveBook').onclick=()=>{const b=book($('bookKey').value);if(!b)return;b.title=$('bookTitle').value.trim()||b.file||'未命名';b.author=$('bookAuthor').value.trim();b.category=$('bookCategory').value.trim();b.progress=Math.max(0,Math.min(100,+$('bookProgress').value||0));b.status=b.progress>=100?'done':b.progress>0?'reading':'unread';save();renderAll();closeSheets();toast('书籍资料已保存')};
$('challengeStart').onchange=e=>{if(e.target.value)state.challengeStart=e.target.value;save();renderCalendar()};$('challengeEnd').onchange=e=>{if(e.target.value&&e.target.value>=state.challengeStart)state.challengeEnd=e.target.value;else{toast('结束日期不能早于开始日期');e.target.value=state.challengeEnd}save();renderCalendar()};$('colorRow').onclick=e=>{const b=e.target.closest('[data-color]');if(!b)return;state.accent=b.dataset.color;save();applyAccent()};$('customColor').oninput=e=>{state.accent=e.target.value;save();applyAccent()};
$('exportBackup').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`阅迹备份-${todayKey}.json`;a.click();URL.revokeObjectURL(a.href)};$('importBackup').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{state=normalize(JSON.parse(await f.text()));save();renderAll();toast('网页备份已导入')}catch(err){toast('这个 JSON 无法读取')}};$('loadDemo').onclick=()=>{if(confirm('恢复演示数据会覆盖当前网页记录，继续吗？')){state=clone(demo);save();renderAll();toast('已恢复演示数据')}};
function cleanTitle(v){return String(v||'').replace(/\.(epub|mobi|azw3?|pdf|txt|cbz|cbr)$/i,'').trim()||'未命名书籍'}
function pickCol(cols,tests){return cols.find(c=>tests.some(t=>t.test(c.toLowerCase())))}
async function parseSqlite(bytes){const SQL=await initSqlJs();const db=new SQL.Database(new Uint8Array(bytes));const tables=db.exec("SELECT name FROM sqlite_master WHERE type='table'")[0]?.values.flat()||[];let books=[],sessions=[];for(const tn of tables){let info;try{info=db.exec(`PRAGMA table_info(\"${String(tn).replace(/"/g,'""')}\")`)[0]}catch(e){continue}if(!info)continue;const cols=info.values.map(r=>String(r[1])),title=pickCol(cols,[/book.*name/,/^name$/,/^title$/, /filename/]),date=pickCol(cols,[/^date$/, /read.*date/,/time/,/day/]),mins=pickCol(cols,[/minute/,/duration/,/read.*time/]),words=pickCol(cols,[/word/,/char/]),progress=pickCol(cols,[/progress/,/percent/]),author=pickCol(cols,[/author/]);if(title){let rows;try{rows=db.exec(`SELECT * FROM \"${String(tn).replace(/"/g,'""')}\" LIMIT 5000`)[0]}catch(e){continue}if(!rows)continue;const idx=Object.fromEntries(rows.columns.map((c,i)=>[c,i]));for(const r of rows.values){const raw=r[idx[title]];if(raw==null)continue;let dval=date?r[idx[date]]:null,dk='';if(dval){if(typeof dval==='number'){const ms=dval>1e12?dval:dval>1e9?dval*1000:null;if(ms)dk=dateKey(new Date(ms))}else{const m=String(dval).match(/(20\d{2})[-\/]?(\d{1,2})[-\/]?(\d{1,2})/);if(m)dk=`${m[1]}-${pad(m[2])}-${pad(m[3])}`}}const key='moon-'+btoa(unescape(encodeURIComponent(String(raw)))).replace(/[^a-z0-9]/gi,'').slice(0,24);if(!books.some(b=>b.key===key))books.push({key,title:cleanTitle(raw),file:String(raw),author:author?String(r[idx[author]]||''):'',category:'',country:'',birth:'',progress:progress?Math.min(100,+r[idx[progress]]||0):0,status:'reading',minutes:0,words:0,days:0,color:palette[books.length%palette.length]});if(dk)sessions.push({date:dk,bookKey:key,minutes:mins?Math.max(0,+r[idx[mins]]||0):0,words:words?Math.max(0,+r[idx[words]]||0):0})}}}
 db.close();if(!books.length)throw new Error('未找到可识别的书籍表');return{books,sessions}}
async function importMoon(file){$('importStatus').textContent='正在本地读取备份……';try{const zip=await JSZip.loadAsync(file),names=Object.keys(zip.files).filter(n=>!zip.files[n].dir),dbName=names.find(n=>/\.(db|sqlite|sqlite3)$/i.test(n))||names.find(n=>/database|book|stat/i.test(n)),jsonName=names.find(n=>/\.json$/i.test(n));let data;if(dbName)data=await parseSqlite(await zip.file(dbName).async('arraybuffer'));else if(jsonName){const obj=JSON.parse(await zip.file(jsonName).async('text'));data={books:obj.books||[],sessions:obj.sessions||[]}}else throw new Error('备份中没有找到可读取的数据库');if(!data.books.length)throw new Error('没有识别到书籍');const byKey={};data.sessions.forEach(s=>{if(!byKey[s.bookKey])byKey[s.bookKey]=[];byKey[s.bookKey].push(s)});data.books.forEach(b=>{const ss=byKey[b.key]||[];b.minutes=ss.reduce((a,s)=>a+(+s.minutes||0),0);b.words=ss.reduce((a,s)=>a+(+s.words||0),0);b.days=new Set(ss.map(s=>s.date)).size});state.books=data.books;state.sessions=data.sessions;state.source='静读天下';state.importedAt=new Date().toISOString();save();renderAll();$('importStatus').textContent=`已识别 ${data.books.length} 本书、${new Set(data.sessions.map(s=>s.date)).size} 个阅读日。` ;toast('静读天下备份已导入')}catch(err){$('importStatus').textContent=`没有成功解析：${err.message}。你的备份不会被上传或改动。`;toast('导入失败')}}
$('mrproFile').onchange=e=>{const f=e.target.files[0];if(f)importMoon(f)};
function moonKey(v){let h=2166136261;for(const c of String(v||'').toLowerCase()){h^=c.codePointAt(0);h=Math.imul(h,16777619)}return'moon-'+(h>>>0).toString(36)}
function sqlRows(db,sql){const out=db.exec(sql)[0];if(!out)return[];return out.values.map(r=>Object.fromEntries(out.columns.map((c,i)=>[c,r[i]])))}
function moonDate(ms){const d=new Date(+ms||0);return Number.isNaN(d.getTime())||d.getFullYear()<2000?todayKey:dateKey(d)}
function dayNumberDate(n){const d=new Date(+n*86400000);return Number.isNaN(d.getTime())?'':d.toISOString().slice(0,10)}
async function parseMoonDatabase(bytes){const SQL=await initSqlJs();const db=new SQL.Database(new Uint8Array(bytes));const tables=new Set(sqlRows(db,"SELECT name FROM sqlite_master WHERE type='table'").map(x=>x.name));if(!tables.has('books')||!tables.has('notes')){db.close();throw new Error('没有找到静读天下书目和书摘表')}const bookRows=sqlRows(db,'SELECT * FROM books'),noteRows=sqlRows(db,'SELECT * FROM notes'),statRows=tables.has('statistics')?sqlRows(db,'SELECT * FROM statistics'):[];const books=[],aliases=new Map();function addBook(title,filename,author='',category=''){const identity=String(filename||title||'').toLowerCase(),key=moonKey(identity),found=books.find(b=>b.key===key);if(found)return found;const b={key,title:String(title||cleanTitle(filename)),file:String(filename||''),author:String(author||''),category:String(category||''),progress:0,status:'unread',minutes:0,words:0,days:0,color:palette[books.length%palette.length]};books.push(b);[filename,String(filename||'').toLowerCase(),title].filter(Boolean).forEach(x=>aliases.set(String(x).toLowerCase(),b));return b}bookRows.forEach(r=>addBook(r.book,r.filename,r.author,r.category));function resolve(title,filename){return aliases.get(String(filename||'').toLowerCase())||aliases.get(String(title||'').toLowerCase())||addBook(title,filename)}const highlights=noteRows.filter(r=>String(r.original||'').trim()||String(r.note||'').trim()).map(r=>{const b=resolve(r.book,r.filename),time=+r.time||0;return{id:`moon-note-${r._id}-${moonKey(r.filename)}`,bookKey:b.key,date:moonDate(time),time,quote:String(r.original||''),note:String(r.note||''),bookmark:String(r.bookmark||''),color:r.highlightColor,underline:!!r.underline,strikethrough:!!r.strikethrough}});const sessions=[];for(const r of statRows){const b=resolve('',r.filename);for(const line of String(r.dates||'').split(/\r?\n/)){const m=line.match(/^(\d+)\|(\d+)@(\d+)/);if(!m)continue;const date=dayNumberDate(m[1]);if(date)sessions.push({date,bookKey:b.key,minutes:Math.round(+m[2]/60000),words:+m[3]||0,source:'moon'})}}const combined=new Map();sessions.forEach(s=>{const k=`${s.date}|${s.bookKey}`,old=combined.get(k)||{...s,minutes:0,words:0};old.minutes+=s.minutes;old.words+=s.words;combined.set(k,old)});const finalSessions=[...combined.values()],byKey={};finalSessions.forEach(s=>(byKey[s.bookKey]||(byKey[s.bookKey]=[])).push(s));books.forEach(b=>{const ss=byKey[b.key]||[];b.minutes=ss.reduce((a,s)=>a+s.minutes,0);b.words=ss.reduce((a,s)=>a+s.words,0);b.days=new Set(ss.map(s=>s.date)).size;b.status=ss.length?'reading':'unread'});db.close();return{books,sessions:finalSessions,highlights}}
async function databaseFromBackup(file){const zip=await JSZip.loadAsync(file),names=Object.keys(zip.files).filter(n=>!zip.files[n].dir);let dbName=names.find(n=>/(^|\/)mrbooks\.db$/i.test(n))||names.find(n=>/\.(db|sqlite|sqlite3)$/i.test(n));if(!dbName){const manifest=names.find(n=>/(^|\/)_names\.list$/i.test(n));if(manifest){const lines=(await zip.file(manifest).async('text')).replace(/^\uFEFF/,'').split(/\r?\n/),index=lines.findIndex(n=>/(^|\/)mrbooks\.db(?:$|\?)/i.test(n));if(index>=0){const dir=manifest.slice(0,manifest.lastIndexOf('/')+1),tag=`${dir}${index+1}.tag`;if(zip.file(tag))dbName=tag}}}if(!dbName)throw new Error('备份中没有找到 mrbooks.db');return zip.file(dbName).async('arraybuffer')}
let pendingMoonImport=null;
async function importMoonV2(file){$('importStatus').textContent='正在本地读取备份……';$('importPreview').hidden=true;pendingMoonImport=null;try{const data=await parseMoonDatabase(await databaseFromBackup(file));pendingMoonImport=data;const days=new Set(data.sessions.map(s=>s.date)).size,comments=data.highlights.filter(h=>h.note.trim()).length;$('importPreviewText').innerHTML=`<b>已经读取完成，尚未写入网页</b><div class="preview-grid"><span><strong>${data.books.length}</strong> 本书</span><span><strong>${data.highlights.length}</strong> 条书摘</span><span><strong>${comments}</strong> 条批注</span><span><strong>${days}</strong> 个阅读日</span></div><p>确认后会与现有记录合并；重复导入不会重复添加同一条书摘。</p>`;$('importStatus').textContent=`文件：${file.name} · 全程在当前浏览器内解析。`;$('importPreview').hidden=false}catch(err){$('importStatus').textContent=`没有成功解析：${err.message}。现有数据没有变化。`;toast('导入失败')}}
function mergeMoon(data){const base=state.source==='演示数据'?{...state,books:[],sessions:[],journals:{},highlights:[]}:state,bookMap=new Map(base.books.map(b=>[b.key,b]));data.books.forEach(b=>{const old=bookMap.get(b.key);bookMap.set(b.key,old?{...b,...old,file:old.file||b.file,author:old.author||b.author,category:old.category||b.category,minutes:b.minutes,words:b.words,days:b.days,status:+old.progress>0?old.status:b.status}:b)});const sessions=new Map(base.sessions.map(s=>[`${s.date}|${s.bookKey}`,s]));data.sessions.forEach(s=>sessions.set(`${s.date}|${s.bookKey}`,s));const highlights=new Map((base.highlights||[]).map(h=>[h.id,h]));data.highlights.forEach(h=>highlights.set(h.id,h));state=normalize({...base,books:[...bookMap.values()],sessions:[...sessions.values()],highlights:[...highlights.values()],source:'静读天下',importedAt:new Date().toISOString()});save();renderAll()}
$('confirmMoonImport').onclick=()=>{if(!pendingMoonImport)return;const count=pendingMoonImport.highlights.length;mergeMoon(pendingMoonImport);pendingMoonImport=null;$('importPreview').hidden=true;$('mrproFile').value='';$('importStatus').textContent=`导入完成：当前共有 ${state.books.length} 本书、${state.highlights.length} 条静读书摘。`;toast(`已导入 ${count} 条书摘`)};
$('cancelMoonImport').onclick=()=>{pendingMoonImport=null;$('importPreview').hidden=true;$('mrproFile').value='';$('importStatus').textContent='已取消，网页数据没有变化。'};
$('mrproFile').onchange=e=>{const f=e.target.files[0];if(f)importMoonV2(f)};
function renderAll(){applyAccent();$('sourcePill').textContent=state.source||'网页记录';renderBookOptions();renderToday();renderLibrary();renderNotes();if(page==='analytics')renderAnalytics();if(page==='monthly')renderMonthly()}
renderAll();
